### ISSUE TITLE
Presentatie Interbestuurlijke werkgroep Functioneel Annoteren 17-05-2019.

### ISSUE THREAD

**Issue by GijsKoedam** [Geonovum/TPOD#10]
**Presentatie op 17 mei 2019 voor de Interbestuurlijke werkgroep Functioneel Annoteren**

Toelichting: PR04 heeft op 17 mei een toelichting gegeven over hoe het mechanisme van annoteren werkt en de wijze waarop geannoteerd kan worden. Deze presentatie geeft ook voor alle andere belanghebbenden een goed inzicht over het annoteren

[Presentatie interbestuurlijke werkgroep functioneel annoteren 2019-05-17.pptx](https://github.com/Geonovum/TPOD/files/3281474/Presentatie.interbestuurlijke.werkgroep.functioneel.annoteren.2019-05-17.pptx)

**Comment by wilkoquak** [comment]
Ik zie dat de issue lijst gebruikt is om presentaties te delen. Omdat informatie niet meer actueel is close ik het issue.
