### ISSUE TITLE
Presentatie stand van zaken CIMOW Sprint 5 PI-10 - 11-06-2019

### ISSUE THREAD

**Issue by GijsKoedam** [Geonovum/TPOD#11]
**Presentatie over de stand van zaken rond CIMOW en IMOW voor de Sprintdemo van Sprint 5 in PI-10 op 11 juni 2019**

Toelichting: Tijdens de tweewekelijkse Sprintdemo heeft PR04 de stand van zaken gepresenteerd over de ontwikkeling van het IMOW en de kwesties die nog uitgewerkt zullen worden. 

[CIMOW verwerken in TPOD PR04 Sprint 5 PI-10.pptx](https://github.com/Geonovum/TPOD/files/3281507/CIMOW.verwerken.in.TPOD.PR04.Sprint.5.PI-10.pptx)

**Comment by wilkoquak** [comment]
Dit is een issue waarin een presentatie wordt gedeeld. Er is verder geen actie nodig en ik sluit dus het issue.
