### ISSUE TITLE
Presentatie over annoteren

### ISSUE THREAD

**Issue by MVS11** [Geonovum/TPOD#4]
Deze presentatie is bedoeld om meer uitleg te geven over annoteren. Opmerkingen of vragen zijn van harte welkom. 

[Presentatie Annoteren eindversie.pptx](https://github.com/Geonovum/TPOD/files/3088510/Presentatie.Annoteren.eindversie.pptx)

**Comment by Rkoenders** [comment]
Deze presentatie focust op de gevolgen van annoteren binnen het DSO-LV. Maar je zou ook breder moeten kijken. Netjes geannoteerde data krijgt kenmerken met zich mee voor o.a.

- gebruik in GIS systemen
- gebruik in VTH systemen
- gebruik in plansystemen
En let wel: alle digitale ruimtelijke plannen van nu zijn al behoorlijk geannoteerd. Als je niet annoteerd heb je helemaal niets van dit alles over.

**Comment by CBarreveld** [comment]
Dank je Remco, voor je toevoeging. De presentatie wordt aangepast en deze toevoeging wordt daarin meegenomen.

**Comment by wilkoquak** [comment]
Dit is een issue waarin een presentatie wordt gedeeld. Er is verder geen actie nodig en ik sluit dus het issue.
