### ISSUE TITLE
Verdiepingssessie Annoteren op 1 mei

### ISSUE THREAD

**Issue by CBarreveld** [Geonovum/TPOD#7]
Op 1 mei vindt van 09.30-12.00 uur de verdiepingssessie Annoteren plaats. 
De twee hoofdonderwerpen die besproken zullen worden zijn: 
- Annoteren
- Toepassing van werkingsgebieden

Hieronder is de input te vinden voor deze sessie. 
[Prioriteit 3 voorstel-annotaties.docx](https://github.com/Geonovum/TPOD/files/3117387/Prioriteit.3.voorstel-annotaties.docx)
[Prioriteit 3B  reactie voorstel-annotaties.docx](https://github.com/Geonovum/TPOD/files/3117389/Prioriteit.3B.reactie.voorstel-annotaties.docx)
[Prioriteit 5 Verwerkingsgebieden.docx](https://github.com/Geonovum/TPOD/files/3117390/Prioriteit.5.Verwerkingsgebieden.docx)

**Comment by wilkoquak** [comment]
Dit is een issue waarin een presentatie wordt gedeeld. Er is verder geen actie nodig en ik sluit dus het issue. De presentatie is nog steeds te vinden bij de gesloten issues.
