### ISSUE TITLE
Koppelingsconstructie AMvB-MR

### ISSUE THREAD

**Issue by CBarreveld** [Geonovum/TPOD#8]
In sprint 2 van PI10 heeft PR04 de koppeling van regels uit AMvBs aan begrenzingen uit de MR verwerkt in ene werkversie van de TPOD AMvB-MR. Bijgevoegde presentatie laat zien welke oplossing het mogelijk maakt regels uit de AMvBs te koppelen aan begrenzingen uit de MR, zonder dat er een wijzigingsbesluit op de betreffende AMvB(s) hoeft plaats te vinden.
De verwerkte oplossing is besproken met EB/BZK. 
 
[AMvB-MR koppelingsconstructie.pdf](https://github.com/Geonovum/TPOD/files/3146818/AMvB-MR.koppelingsconstructie.pdf)

**Comment by wilkoquak** [comment]
Dit is een issue waarin een presentatie wordt gedeeld. Er is verder geen actie nodig en ik sluit dus het issue. De presentatie is nog steeds te vinden bij de gesloten issues.
