### ISSUE TITLE
Lidnummering

### ISSUE THREAD

**Issue by Rkoenders** [Geonovum/TPOD#9]
In TPOD omgvingsplan 0.97.1.1 wordt voor de lidnummering aangegeven:
Nummer: Leden worden per artikel oplopend genummerd in Arabische cijfers, waarbij het eerste lid van ieder artikel het nummer 1 krijgt. Achter het cijfer komt een punt.

Wat gebeurt er als er iemand een lid wil toevoegen tussen lid 1 en lid 2?

**Comment by CBarreveld** [comment]
Hoi Remco, je vraag is uitgezet alleen duurt de beantwoording wat langer waardoor ik je hiermee wil laten weten dat het onder behandeling is. Ik hoop begin volgende week een inhoudelijke reactie te kunnen geven.

**Comment by RicharddeGraaf1** [comment]
Bij tussenvoegen van leden kan de gebruiker ervoor kiezen om bijvoorbeeld 1a en 1b te gebruiken. Hernummeren is dus niet nodig. De wId zorgt ervoor dat altijd verwezen kan worden naar het juiste lid.

**Comment by RicharddeGraaf1** [comment]
(Dit is het gereviewde antwoord vanuit het team dat werkt aan de TPOD's.)
Zoals uit de navolgende norm blijkt bestaat de nummering van Hoofdstuk, Titel, Afdeling, Paragraaf, Subparagraaf, Subsubparagraaf, Artikel en Lid uit Arabische cijfers. Daaraan worden geen letters toegevoegd. Dat betekent dat wanneer met een wijzigingsbesluit een nieuw tekstelement wordt toegevoegd of een bestaand tekstelement wordt verwijderd, in de geconsolideerde versie vernummering van de daaropvolgende tekstelementen van hetzelfde type plaatsvindt. Wanneer bijvoorbeeld in een reeks artikelen 2.1 t/m 2.6 na artikel 2.1 een nieuw artikel wordt toegevoegd, dat nieuwe artikel het nummer 2.2 krijgt en de bestaande artikelen 2.2 t/m 2.6 worden vernummerd tot 2.3 t/m 2.7. Bij opsommingen vindt overeenkomstige toepassing van dit principe plaats, zij het dan in de vorm van letters, arabische en Romeinse cijfers.

**Comment by wilkoquak** [comment]
Remco, ik zie dat dit issue nog steeds open, maar dat er wel een gereviewed antwoord gegeven is. Ik sluit dus dit issue. En ga ook proberen deze mogelijkheid tot het openen van issues te sluiten want momenteel is het kanaal hiervoor te vinden op de [meldingen ](https://www.geonovum.nl/geo-standaarden/omgevingswet#meldingen)pagina
